### ISSUE TITLE
GitHub Membership Request for AnnIsaacs7

### ISSUE THREAD

**Issue by AnnIsaacs7** [Roman-Supernova-PIT/romansn-management#1]
- Github Username: AnnIsaacs7
- What working group access do you need?
    - [ ] Simulations
    - [ ] Calibration
    - [ ] Photometry
    - [ x ] Spectroscopy
    - [ ] Other:

**Comment by benjaminrose** [comment]
Invitation sent. Let me know if there are any more problems.
