### ISSUE TITLE
GitHub Membership Request for [jmderkacy]

### ISSUE THREAD

**Issue by jmderkacy** [Roman-Supernova-PIT/romansn-management#2]
- Github Username: jmderkacy
- What working group access do you need?
    - [ ] Simulations
    - [X] Calibration
    - [ ] Photometry
    - [X] Spectroscopy
    - [ ] Other:

Note: New postdoc at STScI working with Russell Ryan on spectroscopy aspects of PIT

**Comment by benjaminrose** [comment]
Invitation has been sent.
